name = "nextjs-expo-monorepo-api"
main = "src/index.ts"
compatibility_date = "2025-07-18"

# ローカル開発用の環境変数
[vars]
CORS_ORIGINS = "http://localhost:3000,http://localhost:8081,http://localhost:19006"
NODE_ENV = "development"

[env.development]
name = "nextjs-expo-monorepo-api-dev"
[env.development.vars]
CORS_ORIGINS = "http://localhost:3000,http://localhost:8081,http://localhost:19006"
NODE_ENV = "development"

[env.production]
name = "nextjs-expo-monorepo-api-prod"
[env.production.vars]
CORS_ORIGINS = "https://yourapp.com,https://www.yourapp.com"
NODE_ENV = "production"
# 本番環境の秘密情報は wrangler.local.toml または Cloudflare Dashboard で設定